const categories = [
  { id: 'community', icon: './assets/icons/community.png', fa: 'گروه‌ها' },
  { id: 'jobs', icon: './assets/icons/jobs.png', fa: 'کار و اسپانسر' },
  { id: 'events', icon: './assets/icons/events.png', fa: 'رویدادها' },
  { id: 'business', icon: './assets/icons/business.png', fa: 'کسب‌وکار' },
  { id: 'activities', icon: './assets/icons/activities.png', fa: 'تفریح' },
  { id: 'news', icon: './assets/icons/news.png', fa: 'خبر' },
  { id: 'visas', icon: './assets/icons/visas.png', fa: 'ویزاها' },
  { id: 'market', icon: './assets/icons/market.png', fa: 'دست‌دوم' },
];

const listings = [
  { id: 1, type: 'business', logo: 'ع', fa: 'رستوران ایرانی علی‌قاپو', en: 'Ali Qapu Persian Restaurant', placeFa: 'ملبورن · غذای ایرانی و سالن مراسم', placeEn: 'Melbourne · Persian dining and functions', verified: false, sourceName: 'وب‌سایت رسمی علی‌قاپو', sourceUrl: 'https://thealiqapu.com/', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'رستوران ایرانی با منوی غذاهای سنتی و فضای برگزاری مهمانی و مراسم. جزئیات نشانی و رزرو را پیش از مراجعه در وب‌سایت خود مجموعه بررسی کنید.' },
  { id: 2, type: 'business', logo: 'پ', fa: 'پرشین فلیورز', en: 'Persian Flavours', placeFa: '۳۳۸ اسپرینگ‌ویل رود، فارست هیل', placeEn: '338 Springvale Road, Forest Hill', verified: false, sourceName: 'وب‌سایت رسمی Persian Flavours', sourceUrl: 'https://persian-flavours.com.au/', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'رستوران و غذای بیرون‌بر ایرانی در فارست هیل. منو و اطلاعات تماس را در سایت رسمی مجموعه ببینید.' },
  { id: 3, type: 'business', logo: 'ح', fa: 'قصابی و سوپرمارکت حلال ایرانی', en: 'Persian Halal Butchery & Grocery', placeFa: 'دانکستر ایست و باکس هیل نورث', placeEn: 'Doncaster East and Box Hill North', verified: false, sourceName: 'وب‌سایت رسمی Persian Halal', sourceUrl: 'https://persianhalal.com.au/', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'گوشت حلال و مواد غذایی ایرانی با دو شعبه در شرق ملبورن؛ نشانی‌های اعلام‌شده در سایت رسمی: Jackson Court دانکستر ایست و Station Street باکس هیل نورث.' },
  { id: 4, type: 'business', logo: 'ز', fa: 'سوپرمارکت زمزم', en: 'ZamZam Supermarket', placeFa: 'نورث‌کوت پلازا، نورث‌کوت', placeEn: 'Northcote Plaza, Northcote', verified: false, sourceName: 'وب‌سایت رسمی زمزم', sourceUrl: 'https://www.zamzam-supermarket-herbals.com.au/', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'سوپرمارکت مواد غذایی ایرانی و خاورمیانه‌ای در نورث‌کوت پلازا. موجودی و ساعت کار ممکن است تغییر کند.' },
  { id: 5, type: 'business', logo: 'هـ', fa: 'هایپر پاندا', en: 'Hyper Panda', placeFa: 'فروشگاه آنلاین · تحویل در ملبورن', placeEn: 'Online store · Melbourne delivery', verified: false, sourceName: 'وب‌سایت رسمی Hyper Panda', sourceUrl: 'https://www.hyperpanda.com.au/', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'فروشگاه آنلاین مواد غذایی خاورمیانه‌ای با گزینه‌های تحویل و دریافت حضوری در ملبورن.' },
  { id: 6, type: 'business', logo: 'پ', fa: 'فروشگاه پوزی', en: 'Pozy Persian Grocery', placeFa: 'آنلاین · ارسال در استرالیا', placeEn: 'Online · Australia-wide delivery', verified: false, sourceName: 'وب‌سایت رسمی Pozy', sourceUrl: 'https://www.pozy.com.au/about', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'فروشگاه آنلاین خانوادگی ایرانی-استرالیایی برای مواد غذایی ایرانی با ارسال در سراسر استرالیا.' },
  { id: 20, type: 'events', logo: 'ش', image: './assets/events/royal-show.webp', imageAlt: 'نمایشگاه سلطنتی ملبورن', fa: 'نمایشگاه سلطنتی ملبورن ۲۰۲۶', en: 'Melbourne Royal Show 2026', placeFa: '۲۴ سپتامبر تا ۴ اکتبر · Melbourne Showgrounds', placeEn: '24 September–4 October · Melbourne Showgrounds', verified: false, sourceName: 'Melbourne Royal', sourceUrl: 'https://royalshow.com.au/', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'نمایش سالانه ملبورن با حیوانات، خوراکی‌ها، سرگرمی و برنامه‌های خانوادگی. زمان‌بندی و بلیت را از برگزارکننده رسمی بررسی کنید.' },
  { id: 21, type: 'events', logo: 'ف', image: './assets/events/melbourne-fringe.webp', imageAlt: 'اجرای زنده در فستیوال فرینج ملبورن', fa: 'فستیوال فرینج ملبورن ۲۰۲۶', en: 'Melbourne Fringe Festival 2026', placeFa: '۲۹ سپتامبر تا ۱۸ اکتبر · نقاط مختلف ملبورن', placeEn: '29 September–18 October · Across Melbourne', verified: false, sourceName: 'Melbourne Fringe', sourceUrl: 'https://www.melbournefringe.com.au/festival-info/festival-faqs', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'فستیوال هنرهای مستقل ملبورن با اجراها و برنامه‌ها در نقاط مختلف شهر. برنامه کامل و دسترسی هر اجرا را در سایت رسمی ببینید.' },
  { id: 22, type: 'events', logo: 'ب', image: './assets/events/winter-night-market.webp', imageAlt: 'بازار شبانه زمستانی کویین ویکتوریا', fa: 'بازار شبانه زمستانی', en: 'Winter Night Market', placeFa: 'تا ۹ سپتامبر · Queen Victoria Market', placeEn: 'Until 9 September · Queen Victoria Market', verified: false, sourceName: 'Queen Victoria Market', sourceUrl: 'https://qvm.com.au/whats-on/winter-night-market-2/', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'بازار شبانه زمستانی با غذا، نوشیدنی و سرگرمی در بازار کویین ویکتوریا. جزئیات روز و ساعت را در صفحه رسمی بازار چک کنید.' },
  { id: 23, type: 'events', logo: 'ن', image: './assets/events/ngv-friday-nights.webp', imageAlt: 'پوستر رسمی شب‌های جمعه NGV و نمایشگاه کارتیه', fa: 'شب‌های جمعه NGV: کارتیه', en: 'NGV Friday Nights: Cartier', placeFa: 'تا ۲ اکتبر، جمعه‌ها ۶ تا ۱۰ شب · NGV', placeEn: 'Until 2 October, Fridays 6–10pm · NGV', verified: false, sourceName: 'NGV', sourceUrl: 'https://www.ngv.vic.gov.au/friday-nights/', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'برنامه شبانه جمعه‌های گالری ملی ویکتوریا همراه با نمایشگاه کارتیه و اجراهای زنده. این برنامه بلیت‌دار است.' },
  { id: 24, type: 'events', logo: 'ح', image: './assets/events/chocolate-family.webp', imageAlt: 'پنکیک شکلاتی رویداد خانوادگی ملبورن', fa: 'روز ماجراجویی شکلاتی خانواده', en: 'Chocolate Family Adventure Day', placeFa: 'تا ۲۷ سپتامبر · داکلندز', placeEn: 'Until 27 September · Docklands', verified: false, sourceName: 'What’s On Melbourne', sourceUrl: 'https://whatson.melbourne.vic.gov.au/things-to-do/chocolate-family-adventure-day', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'یک تجربه خانوادگی شکلات‌محور در داکلندز. تاریخ‌ها، ظرفیت و هزینه را در فهرست رسمی شهر بررسی کنید.' },
  { id: 30, type: 'activities', logo: 'م', fa: 'شبانه: موزه بعد از تاریکی', en: 'Nocturnal: Museum After Dark', placeFa: 'تا ۵ نوامبر · Melbourne Museum', placeEn: 'Until 5 November · Melbourne Museum', verified: false, sourceName: 'What’s On Melbourne', sourceUrl: 'https://whatson.melbourne.vic.gov.au/things-to-do/whats-on-september', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'بازدید شبانه از موزه ملبورن با برنامه‌های ویژه بزرگسالان. جزئیات هر نوبت و بلیت را در منبع رسمی ببینید.' },
  { id: 31, type: 'activities', logo: 'ط', fa: 'تور شبانه طعم‌های ملبورن', en: 'Flavours of Melbourne Night Trail', placeFa: 'تا ۲۹ اکتبر · مرکز ملبورن', placeEn: 'Until 29 October · Melbourne CBD', verified: false, sourceName: 'What’s On Melbourne', sourceUrl: 'https://whatson.melbourne.vic.gov.au/things-to-do/whats-on-september', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'تور پیاده‌روی شبانه برای آشنایی با غذاها و محله‌های مرکز ملبورن. زمان و نقطه شروع را هنگام رزرو تأیید کنید.' },
  { id: 32, type: 'activities', logo: 'ر', fa: 'کلاس‌های هنر رزین', en: 'Resin Art Classes', placeFa: 'تا ۳۱ دسامبر · ملبورن', placeEn: 'Until 31 December · Melbourne', verified: false, sourceName: 'What’s On Melbourne', sourceUrl: 'https://whatson.melbourne.vic.gov.au/things-to-do/whats-on-september', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'کلاس‌های ساخت آثار رزینی برای تجربه‌ای خلاقانه. سطح دوره، محل و هزینه به سانس انتخابی بستگی دارد.' },
  { id: 33, type: 'activities', logo: 'س', fa: 'داستان تصویر متحرک', en: 'The Story of the Moving Image', placeFa: 'تا ۳۱ دسامبر · ACMI، فدریشن اسکوئر', placeEn: 'Until 31 December · ACMI, Federation Square', verified: false, sourceName: 'What’s On Melbourne', sourceUrl: 'https://whatson.melbourne.vic.gov.au/things-to-do/whats-on-september', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'نمایش دائمی ACMI درباره تاریخ و فرهنگ فیلم، تلویزیون، بازی و هنر دیجیتال در فدریشن اسکوئر.' },
  { id: 40, type: 'news', logo: 'م', fa: 'درخواست عضویت کمیته مشورتی چندفرهنگی', en: 'Multicultural Advisory Committee applications', placeFa: 'مهلت: ۴ سپتامبر ۲۰۲۶ · City of Melbourne', placeEn: 'Closes 4 September 2026 · City of Melbourne', verified: false, sourceName: 'Participate Melbourne', sourceUrl: 'https://participate.melbourne.vic.gov.au/', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'شهر ملبورن برای کمیته مشورتی چندفرهنگی درخواست عضویت می‌پذیرد. طبق صفحه رسمی، مهلت تا ساعت ۱۱:۴۵ شب جمعه ۴ سپتامبر است.' },
  { id: 41, type: 'news', logo: 'هـ', fa: 'نظرخواهی درباره مراکز داده و زیرساخت هوش مصنوعی', en: 'Data centres and AI infrastructure consultation', placeFa: 'تا ۳۰ سپتامبر · City of Melbourne', placeEn: 'Until 30 September · City of Melbourne', verified: false, sourceName: 'Participate Melbourne', sourceUrl: 'https://participate.melbourne.vic.gov.au/', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'شهر ملبورن درباره پیش‌نویس موضع‌نامه مراکز داده و زیرساخت هوش مصنوعی نظر عمومی دریافت می‌کند.' },
  { id: 42, type: 'news', logo: 'ا', fa: 'برنامه نمایشگاه سلطنتی ملبورن اعلام شد', en: 'Melbourne Royal Show program announced', placeFa: 'خبر برگزارکننده · ۳۰ اوت ۲۰۲۶', placeEn: 'Organiser update · 30 August 2026', verified: false, sourceName: 'Melbourne Royal', sourceUrl: 'https://royalshow.com.au/its-show-time-new-experiences-exclusive-entertainment-and-thousands-of-animals-at-the-2026-melbourne-royal-show/', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'Melbourne Royal جزئیات تجربه‌ها، سرگرمی‌ها و بخش حیوانات نمایشگاه ۲۰۲۶ را منتشر کرده است.' },
  { id: 43, type: 'news', logo: 'آ', fa: 'پاپ‌آپ‌های اقلیم و محیط‌زیست ملبورن', en: 'Melbourne climate and environment pop-ups', placeFa: '۱۲ سپتامبر تا ۳ اکتبر · چند نقطه شهر', placeEn: '12 September–3 October · Multiple locations', verified: false, sourceName: 'Participate Melbourne', sourceUrl: 'https://participate.melbourne.vic.gov.au/climate-and-environment-strategy/pop-ups', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'چند جلسه حضوری برای گفت‌وگو درباره راهبرد اقلیم و محیط‌زیست، از بازار کویین ویکتوریا تا پارک‌ویل و City Square، اعلام شده است.' },
  { id: 50, type: 'jobs', logo: 'ک', fa: 'دستیار فروش دوزبانه', en: 'Bilingual Sales Assistant', placeFa: 'نمونه نمایشی · پاره‌وقت · ساوت‌بنک', placeEn: 'Prototype example · Part-time · Southbank', verified: false, prototype: true, sourceName: 'نمونه نمایشی', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'نمونه رابط کاربری برای یک آگهی کار دوزبانه. این موقعیت واقعی نیست و امکان اسپانسرشیپ را نشان یا تضمین نمی‌کند.' },
  { id: 51, type: 'jobs', logo: 'ر', fa: 'هماهنگ‌کننده رویداد', en: 'Events Coordinator', placeFa: 'نمونه نمایشی · قراردادی · مرکز ملبورن', placeEn: 'Prototype example · Contract · Melbourne CBD', verified: false, prototype: true, sourceName: 'نمونه نمایشی', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'نمونه رابط کاربری برای موقعیت هماهنگی رویداد. برای انتشار واقعی، هویت کارفرما و جزئیات موقعیت باید بررسی شود.' },
  { id: 52, type: 'jobs', logo: 'پ', fa: 'پشتیبانی مشتری فارسی‌زبان', en: 'Persian-speaking Customer Support', placeFa: 'نمونه نمایشی · دورکاری ترکیبی', placeEn: 'Prototype example · Hybrid', verified: false, prototype: true, sourceName: 'نمونه نمایشی', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'نمونه رابط کاربری برای یک موقعیت پشتیبانی مشتری؛ این آگهی واقعی نیست.' },
  { id: 60, type: 'market', logo: 'م', fa: 'میز مطالعه دست‌دوم', en: 'Second-hand Study Desk', placeFa: 'نمونه نمایشی · ۶۰ دلار · فیتزروی', placeEn: 'Prototype example · $60 · Fitzroy', verified: false, prototype: true, sourceName: 'نمونه نمایشی', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'آگهی نمایشی برای آزمودن صفحه خرید و فروش محلی. این کالا واقعاً برای فروش عرضه نشده است.' },
  { id: 61, type: 'market', logo: 'ص', fa: 'دو صندلی ناهارخوری', en: 'Pair of Dining Chairs', placeFa: 'نمونه نمایشی · ۴۵ دلار · برانزویک', placeEn: 'Prototype example · $45 · Brunswick', verified: false, prototype: true, sourceName: 'نمونه نمایشی', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'آگهی نمایشی برای سنجش چیدمان و فیلترهای دست‌دوم؛ کالای واقعی نیست.' },
  { id: 62, type: 'market', logo: 'د', fa: 'دوچرخه شهری', en: 'City Bicycle', placeFa: 'نمونه نمایشی · ۱۲۰ دلار · کارلتون', placeEn: 'Prototype example · $120 · Carlton', verified: false, prototype: true, sourceName: 'نمونه نمایشی', checked: '۳ سپتامبر ۲۰۲۶', descriptionFa: 'آگهی نمایشی خرید و فروش محلی. پیش از فعال شدن این بخش، سازوکار ایمنی و گزارش تخلف اضافه می‌شود.' },
];

const communitySources = [
  { id: 'melbourne_ir', icon: 'M', fa: 'ملبورن استرالیا', en: 'Melbourne Persian Community', topic: 'city', scope: 'melbourne', members: '≈ 7.4K', url: 'https://t.me/melbourne_ir', descriptionFa: 'گفت‌وگوی عمومی ایرانیان ملبورن و ویکتوریا', descriptionEn: 'Public discussion for Iranians in Melbourne and Victoria' },
  { id: 'jobaustralia', icon: 'ک', fa: 'کاریابی استرالیا', en: 'Jobs Australia', topic: 'jobs', scope: 'australia', members: '≈ 12.2K', url: 'https://t.me/jobaustralia', descriptionFa: 'فرصت شغلی، رزومه، مصاحبه و تجربه کار', descriptionEn: 'Jobs, CVs, interviews and Australian work experience' },
  { id: 'rent_australia', icon: 'خ', fa: 'اجاره خانه استرالیا', en: 'Rent Australia', topic: 'housing', scope: 'australia', members: '≈ 9.1K', url: 'https://t.me/rent_australia', descriptionFa: 'گفت‌وگو و آگهی‌های مرتبط با اجاره و هم‌خانه', descriptionEn: 'Discussion and posts about rentals and share houses' },
  { id: 'studentsaustralia', icon: 'د', fa: 'دانشجویان استرالیا', en: 'Students Australia', topic: 'students', scope: 'australia', members: '≈ 5.7K', url: 'https://t.me/studentsaustralia', descriptionFa: 'جامعه دانشجویان و تجربه تحصیل در استرالیا', descriptionEn: 'Student community and studying in Australia' },
  { id: 'travel_in_au', icon: 'گ', fa: 'استرالیا را باهم بگردیم', en: 'Explore Australia Together', topic: 'activities', scope: 'australia', members: '≈ 7.3K', url: 'https://t.me/travel_in_au', descriptionFa: 'سفر، طبیعت‌گردی و فعالیت‌های گروهی', descriptionEn: 'Travel, outdoors and group activities' },
];

const visaCategories = [
  { id: 'sponsorship', title: 'اسپانسرشیپ کارفرما', description: 'ویزای کاری با حمایت کارفرما', icon: './assets/visa-icons/sponsorship.png' },
  { id: 'work', title: 'کاری و مهارتی', description: 'مسیرهای مهارتی و کاری', icon: './assets/visa-icons/skilled-work.png' },
  { id: 'study', title: 'تحصیلی', description: 'تحصیل و همراه دانشجو', icon: './assets/visa-icons/study.png' },
  { id: 'visit', title: 'توریستی و بازدید', description: 'سفر، دیدار و اقامت کوتاه', icon: './assets/visa-icons/visit.png' },
  { id: 'permanent', title: 'اقامت دائم', description: 'مسیرهای اقامت دائم استرالیا', icon: './assets/visa-icons/permanent.png' },
  { id: 'family', title: 'پارتنر و خانواده', description: 'پیوستن به همسر یا خانواده', icon: './assets/visa-icons/family.png' },
  { id: 'stay-longer', title: 'ماندن بیشتر', description: 'بررسی گزینه‌ها پیش از پایان ویزا', icon: './assets/visa-icons/stay-longer.png' },
  { id: 'other', title: 'سایر ویزاها', description: 'گزینه‌های دیگر در فهرست رسمی', icon: './assets/visa-icons/other.png' },
];

const visaExamples = [
  { id: '482', groups: ['sponsorship', 'work'], title: 'ویزای مهارت مورد نیاز', english: 'Skills in Demand', subclass: '۴۸۲', relevance: 'بالا', tone: 'high', summary: 'ویزای موقت برای نیروی ماهری که یک کارفرمای تأییدشده برای موقعیت شغلی معرفی می‌کند.', stay: 'تا ۴ سال', sponsor: 'لازم است', permanent: 'ممکن است مسیر جداگانه داشته باشد', url: 'https://immi.homeaffairs.gov.au/Visa-subsite/Pages/work/skills-in-demand-482-landing.aspx' },
  { id: '186', groups: ['sponsorship', 'work', 'permanent'], title: 'ویزای نامزدی کارفرما', english: 'Employer Nomination Scheme', subclass: '۱۸۶', relevance: 'متوسط', tone: 'medium', summary: 'اقامت دائم برای نیروی ماهری که کارفرمای استرالیایی واجد شرایط او را معرفی می‌کند.', stay: 'دائم', sponsor: 'لازم است', permanent: 'اقامت دائم', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/employer-nomination-scheme-186' },
  { id: '190', groups: ['work', 'permanent'], title: 'ویزای مهارتی ایالتی', english: 'Skilled Nominated', subclass: '۱۹۰', relevance: 'متوسط', tone: 'medium', summary: 'اقامت دائم برای نیروی ماهری که از سوی یک ایالت یا قلمرو استرالیا نامزد شده باشد.', stay: 'دائم', sponsor: 'نامزدی ایالتی', permanent: 'اقامت دائم', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-nominated-190' },
  { id: '500', groups: ['study'], title: 'ویزای دانشجویی', english: 'Student visa', subclass: '۵۰۰', relevance: 'بررسی', tone: 'high', summary: 'ویزای موقت برای شرکت در دوره تحصیلی واجد شرایط؛ مدت آن به ثبت‌نام و شرایط دوره بستگی دارد.', stay: 'تا ۶ سال، بسته به دوره', sponsor: 'پذیرش و CoE', permanent: 'موقت', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500' },
  { id: '600', groups: ['visit'], title: 'ویزای بازدیدکننده', english: 'Visitor visa — Tourist stream', subclass: '۶۰۰', relevance: 'بررسی', tone: 'high', summary: 'برای گردش، سفر دریایی یا دیدار خانواده و دوستان؛ این مسیر اجازه کار در استرالیا نمی‌دهد.', stay: 'تا ۱۲ ماه', sponsor: 'برای توریستی لازم نیست', permanent: 'موقت', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600/tourist-stream-overseas' },
  { id: '820-801', groups: ['family'], title: 'ویزای پارتنر داخل استرالیا', english: 'Partner visas — onshore', subclass: '۸۲۰ و ۸۰۱', relevance: 'بررسی', tone: 'high', summary: 'برای همسر یا پارتنر واجد شرایطِ شهروند، مقیم دائم استرالیا یا شهروند واجد شرایط نیوزیلند.', stay: 'موقت، سپس بررسی دائم', sponsor: 'پارتنر واجد شرایط', permanent: 'مسیر دو مرحله‌ای', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-onshore' },
];


// Independent short summaries, checked against the linked owner-controlled pages on 8 Sep 2026.
const editorial = [
  {id:101,topic:'events',fa:'نمایشگاه سلطنتی ملبورن؛ ۲۴ سپتامبر تا ۴ اکتبر',en:'Melbourne Royal Show: 24 September–4 October',summaryFa:'یازده روز برنامه خانوادگی، حیوانات، خوراک و سرگرمی در Melbourne Showgrounds.',summaryEn:'Eleven days of family activities, animals, food and entertainment at Melbourne Showgrounds.',bodyFa:'برگزارکننده این تاریخ‌ها را برای نمایشگاه ۲۰۲۶ اعلام کرده است. برنامه هر روز و بلیت را در سایت رسمی بررسی کنید. ویدیوی این پیش‌نمایش یک نمایش تصویری ساخته‌شده برای آزمون رابط است، نه فیلم رویداد.',bodyEn:'The organiser lists these dates for its 2026 show. Check the official daily schedule and tickets before visiting. The preview video is a created visual demo for interface testing, not event footage.',image:'./assets/events/royal-show.webp',video:'./assets/media/australia-demo.mp4',demo:true,source:'Melbourne Royal',url:'https://royalshow.com.au/',checked:'2026-09-08',published:null},
  {id:102,topic:'culture',fa:'فرینج ملبورن از ۲۹ سپتامبر بازمی‌گردد',en:'Melbourne Fringe returns on 29 September',summaryFa:'فستیوال هنرهای مستقل تا ۱۸ اکتبر در ملبورن برگزار می‌شود.',summaryEn:'Melbourne’s independent arts festival runs through 18 October.',bodyFa:'صفحه رسمی جشنواره تاریخ ۲۹ سپتامبر تا ۱۸ اکتبر ۲۰۲۶ را تأیید می‌کند. محل، بلیت و امکانات دسترسی هر اجرا را در برنامه رسمی ببینید.',bodyEn:'The festival’s official FAQ confirms 29 September to 18 October 2026. Consult each event’s official listing for location, tickets and accessibility.',image:'./assets/events/melbourne-fringe.webp',source:'Melbourne Fringe',url:'https://www.melbournefringe.com.au/festival-info/festival-faqs',checked:'2026-09-08',published:null},
  {id:103,topic:'city',fa:'گفت‌وگوی اقلیمی در بازار کویین ویکتوریا',en:'Climate conversation at Queen Victoria Market',summaryFa:'جلسه عمومی ۱۲ سپتامبر از ۱۲:۳۰ تا ۱۴:۳۰ در بخش F بازار برنامه‌ریزی شده است.',summaryEn:'A public pop-up is scheduled on 12 September, 12:30–2:30pm, at the market’s F Shed.',bodyFa:'صفحه رسمی شهر ملبورن، محل این جلسه را کنار Purpose Precinct در F Shed اعلام کرده است. برنامه جلسات دیگر و تغییرات احتمالی را در منبع اصلی بررسی کنید.',bodyEn:'The City of Melbourne lists this session at F Shed, by Purpose Precinct. Check the source for other sessions and any schedule changes.',image:'./assets/images/melbourne-hero.jpg',source:'City of Melbourne',url:'https://participate.melbourne.vic.gov.au/climate-and-environment-strategy/pop-ups',checked:'2026-09-08',published:null}
];
const categoryEnglish={community:'Groups',jobs:'Work & sponsorship',events:'Events',business:'Businesses',activities:'Activities',news:'News',visas:'Visas',market:'Pre-loved'};
categories.forEach(c=>c.en=categoryEnglish[c.id]);
categories.push({id:'exchange',icon:'./assets/icons/exchange.svg',fa:'صرافی',en:'Exchange'});
